### ISSUE TITLE
Failing with error "undefined method `casecmp' for nil:NilClass"

### ISSUE THREAD

**Issue by kylebshr** [bitrise-steplib/steps-ios-auto-provision#105]
I'm getting an error when running this step - any ideas what could be going wrong here?

```
Ensure Provisioning Profiles on Developer Portal
checking xcode managed development profile for target: co (com.company.co) with 1 services on developer portal
downloading development profile: iOS Team Provisioning Profile: com.company.co
checking xcode managed app-store profile for target: co (com.company.co) with 1 services on developer portal
Error:
undefined method `casecmp' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:176:in `distribution_type_matches?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:58:in `block in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:57:in `select'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:57:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:81:in `rescue in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/portal/profile_client.rb:56:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise715203356/step_src/step.rb:90:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision (exit code: 1)                             | 41.93 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
```

**Comment by Roland-Bak** [comment]
Hi there @kylebshr!

Could you please send the logfile of the related build and enable support access (https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) so we might take a closer look? :)

**Comment by kylebshr** [comment]
I think the script was failing because I wasn't actually set up for auto provision. Got everything working now!
