### ISSUE TITLE
Throws Error

### ISSUE THREAD

**Issue by evandelaney** [bitrise-steplib/steps-ios-auto-provision#121]
```
Error:
undefined method `casecmp' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:176:in `distribution_type_matches?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:58:in `block in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:57:in `select'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:57:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:81:in `rescue in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/portal/profile_client.rb:56:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise524216524/step_src/step.rb:90:in `<main>'
```

Not sure what this means

**Comment by evandelaney** [comment]
I have no idea if this is still a problem; I chose to work around it.
