### ISSUE TITLE
Failing with error "undefined method `casecmp' for nil:NilClass"

### ISSUE THREAD

**Issue by wassup-** [bitrise-steplib/steps-ios-auto-provision#131]
For one of my projects, I'm getting the following error when running this step.

```
Error:
undefined method `casecmp' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:176:in `distribution_type_matches?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:58:in `block in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:57:in `select'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:57:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:81:in `rescue in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:56:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/step.rb:90:in `<main>'
```

Full output for this step:
```
+------------------------------------------------------------------------------+

| (0) ios-auto-provision@1                                                     |
+------------------------------------------------------------------------------+
| id: ios-auto-provision                                                       |
| version: 1.5.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2020-08-26T19:19:31Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Successfully installed bundler-1.17.3
Parsing documentation for bundler-1.17.3
Installing ri documentation for bundler-1.17.3
Done installing documentation for bundler after 4 seconds
1 gem installed
$ bundle install
$ bundle exec ruby /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/step.rb
Params:
team_id: XXXXXXXXXX
certificate_urls: ***
min_profile_days_valid: 0
passphrases: 
distribution_type: app-store
project_path: XXXXXXXXXX.xcodeproj
scheme: XXXXXXXXXX-Development
configuration: 
build_url: https://app.bitrise.io/build/7427e1e048936414
build_api_token: ***
keychain_path: /Users/vagrant/Library/Keychains/login.keychain
keychain_password: ***
verbose_log: no
generate_profiles: no
Developer Portal authentication
Session loaded from environment variable is not valid. Continuing with normal login.
authenticated
Downloading Certificates
1 certificate files downloaded, 1 distinct codesign identities included
Identify Certificates on Developer Portal
Distribution certificate found: Apple Distribution: XXXXXXXXXX
Analyzing project
project codesign identity: iPhone Developer
project team id: XXXXXXXXXX
uses xcode managed signing: true
main target's platform: 
target #0: XXXXXXXXXX with 3 services
Matching project codesign identity with the uploaded certificates
using: Apple Distribution: XXXXXXXXXX
Ensure Provisioning Profiles on Developer Portal
checking xcode managed app-store profile for target: XXXXXXXXXX with 3 services on developer portal
Error:
undefined method `casecmp' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:176:in `distribution_type_matches?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:58:in `block in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:57:in `select'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:57:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:81:in `rescue in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/portal/profile_client.rb:56:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise259213736/step_src/step.rb:90:in `<main>'
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | ios-auto-provision@1 (exit code: 1)                           | 1.1 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-ios-auto-provision/issues |
| Source: https://github.com/bitrise-steplib/steps-ios-auto-provision          |
+---+---------------------------------------------------------------+----------+
```

I have tried removing all provisioning profiles from the Apple Developer Portal, and generating new ones using fastlane, but that doesn't change anything. Automatic signing is enabled for this project.

**Comment by bitce** [comment]
Hi @wassup-! Is the same issue present if you set `generate_profiles` to `yes` instead of `no`?

**Comment by wassup-** [comment]
@bitce Yes the issue persists with `generate_profiles` set to `yes`

```
Params:
team_id: XXXXXXXXXX
certificate_urls: ***
min_profile_days_valid: 0
passphrases: 
distribution_type: app-store
project_path: XXXXXXXXXX.xcodeproj
scheme: XXXXXXXXXX-Development
configuration: 
build_url: https://app.bitrise.io/build/4de9e5514aa6e9a5
build_api_token: ***
keychain_path: /Users/vagrant/Library/Keychains/login.keychain
keychain_password: ***
verbose_log: no
generate_profiles: true

Developer Portal authentication
Session loaded from environment variable is not valid. Continuing with normal login.
authenticated
Downloading Certificates
1 certificate files downloaded, 1 distinct codesign identities included
Identify Certificates on Developer Portal
Distribution certificate found: Apple Distribution: XXXXXXXXXX
Analyzing project
project codesign identity: iPhone Developer
project team id: XXXXXXXXXX
uses xcode managed signing: true
main target's platform: 
target #0: XXXXXXXXXX with 3 services
Matching project codesign identity with the uploaded certificates
using: Apple Distribution: XXXXXXXXXX
Ensure Provisioning Profiles on Developer Portal
checking xcode managed app-store profile for target: XXXXXXXXXX with 3 services on developer portal

Error:
undefined method `casecmp' for nil:NilClass
Stacktrace (for debugging):
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:176:in `distribution_type_matches?'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:58:in `block in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:57:in `select'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:57:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:81:in `rescue in ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/portal/profile_client.rb:56:in `ensure_xcode_managed_profile'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise268176616/step_src/step.rb:90:in `<main>'
```

**Comment by bitce** [comment]
Thanks for confirming this. Can you please send a link here to either of these builds and enable Support User access on the Settings of the app?

**Comment by wassup-** [comment]
https://app.bitrise.io/build/3891a54876f64245

Thank you for taking a look at this.

**Comment by Robert-Bitrise** [comment]
Hi @wassup- !
I have checked your build log and I have noticed that you want to auto sign your development project target as an app-store one. For development target you need to have a Development certificate and provisioning profile in your Apple Developer account. Could you please create them and let me know when you are ready? Thank you for your cooperation!

**Comment by wassup-** [comment]
@Robert-Bitrise Do you mean I'm using a wrong `CODE_SIGN_IDENTITY`?

What do you mean by 'development target'? I'm trying to generate a build to distribute via TestFlight. When trying to generate a _staging_ build (to also distribute via TestFlight), the same issue is present (https://app.bitrise.io/build/6000299cc965b722). This is the same flow as most of our apps (we've got development, staging and production environments).

Maybe I'm not understanding what you are saying?

**Comment by Robert-Bitrise** [comment]
@wassup- Please avoid my previous comment, it was not related to your issue. I've fixed your issue, now your workflow still fails but from now your iOS Auto Provision step is working fine. I hope I could help.

**Comment by wassup-** [comment]
@Robert-Bitrise Thank you for your help, I am now able to successfully finish the workflow!

Could you elaborate on what the issue was, and how you fixed it?

**Comment by Robert-Bitrise** [comment]
@wassup- I'm glad I could help :) The issue was in your yml file you had a wrong input value for your iOS Archive step, you have true instead of yes and this caused an issue in the step's source code.

**Comment by Robert-Bitrise** [comment]
@wassup- One more thing, could you please close this ticket if you think we are done? Thank you :)
