### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by kafejo** [bitrise-steplib/steps-ios-auto-provision#31]
I started to get the following error today:

```
Developer Portal authentication
Error:
{"authType"=>"sa"}
aa=C643F815345F9C5438CA6CB194F3; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=apple.com; Path=/; Secure; HttpOnly, acn01=vZQmP3RNZATYW5wPZOVERBYCzAAQPoORz927; Max-Age=31536000; Expires=Wed, 22-May-2019 11:24:50 GMT; Domain=apple.com; Path=/; Secure; HttpOnly
Stacktrace (for debugging):
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/client.rb:469:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/client.rb:653:in `do_login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/client.rb:358:in `login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/client.rb:71:in `login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.88.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise135372514/step_src/lib/autoprovision/portal/auth_client.rb:9:in `login'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise135372514/step_src/lib/autoprovision/auth_helper.rb:31:in `login'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise135372514/step_src/step.rb:18:in `<main>'
|                                                                           
```

Seems like the step fails on authorization. Any ideas?

Step version 1.1.0

**Comment by ghislainfrs** [comment]
It seems you just need to accept the new conditions on the iTunes Connect portal (because of GDPR updates)

**Comment by kafejo** [comment]
Good call. Works after accepting the new conditions. Thanks.

**Comment by HannahCarney** [comment]
Even after accepting terms and conditions this still does not work for me.

**Comment by SupriyaKalghatgi** [comment]
Doesn't work for me either

**Comment by bitce** [comment]
Could you guys send us build URLs to be able to look into your issues? Generally the error should mean that there is something wrong with your ADP connection

**Comment by SupriyaKalghatgi** [comment]
@bitce https://app.bitrise.io/build/c98c024c3c957673
