### ISSUE TITLE
Duplicate profile name sometimes causes the step to fail

### ISSUE THREAD

**Issue by vanwagonet** [bitrise-steplib/steps-ios-auto-provision#39]
https://app.bitrise.io/build/ecfe3e79e1aa4110

```
Apple provided the following error info: There were errors in the data supplied. Please correct and re-submit. Multiple profiles found with the name 'Bitrise ad-hoc - (com.[REDACTED])'.  Please remove the duplicate profiles and try again.
```

This happened while 2 builds were running at the same time. It could be related to concurrency.

**Comment by vanwagonet** [comment]
Another intermittent error: https://app.bitrise.io/build/443f4d7b792ee57e

```
Error:
765: unexpected token at ':'
Stacktrace (for debugging):
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:487:in `fetch_olympus_session'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:457:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:660:in `do_login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:362:in `login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:70:in `login'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise499431385/step_src/lib/autoprovision/portal/auth_client.rb:9:in `login'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise499431385/step_src/lib/autoprovision/auth_helper.rb:31:in `login'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise499431385/step_src/step.rb:25:in `<main>'
```

**Comment by vanwagonet** [comment]
same unexpected token https://app.bitrise.io/build/13ccbef0567653ac

**Comment by bootstraponline** [comment]
Monday, August 6 - Wednesday, August 29
"iOS Student PR" has 40 failed builds out of 66 builds

Parsing errors from 40 logs
https://www.bitrise.io/build/443f4d7b792ee57e failed: ios-auto-provision (exit code: 1)                            
https://www.bitrise.io/build/d16b16d500130fbf failed: ios-auto-provision (exit code: 1)                                       
https://www.bitrise.io/build/b4558531c6a5bcd5 failed: ios-auto-provision (exit code: 1)                            
https://www.bitrise.io/build/2e64abe72e2ae7f1 failed: ios-auto-provision (exit code: 1)                            
https://www.bitrise.io/build/fa2dc20fb1c3aebf failed: ios-auto-provision (exit code: 1)                                       
https://www.bitrise.io/build/ecfe3e79e1aa4110 failed: ios-auto-provision (exit code: 1)                                       
https://www.bitrise.io/build/59a5a49059e5a3de failed: ios-auto-provision (exit code: 1)                                       
https://www.bitrise.io/build/f38098c65b58d728 failed: ios-auto-provision (exit code: 1)                            
https://www.bitrise.io/build/70b5642d782f6066 failed: ios-auto-provision (exit code: 1)

**Comment by godrei** [comment]
Hi @vanwagonet ,
thanks for the issue report, we scheduled to fix this.

**Comment by bwhiteley** [comment]
Is there a workaround on this? I'm blocked on this at the moment.

**Comment by bootstraponline** [comment]
Retrying the failed build is how we're working around it. Bitrise is aware of the problem and will hopefully fix the issue soon.

**Comment by kentcb** [comment]
I'm getting this even without parallel builds. Partial log output is:

```
Ensure Provisioning Profiles on Developer Portal
distribution_types: ["ad-hoc"]
project uses Xcode managed signing, but generate_profiles set to true, trying to generate Provisioning Profiles
checking app for target: Runner (<<redacted>>) on developer portal
sync app services
ensure ad-hoc profile for target: Runner on developer portal
generating ad-hoc profile: Bitrise ad-hoc - (<<redacted>>)
generating ad-hoc profile: Bitrise ad-hoc - (<<redacted>>)
Error:
Apple provided the following error info: There were errors in the data supplied. Please correct and re-submit. Multiple profiles found with the name 'Bitrise ad-hoc - (<<redacted>>)'.  Please remove the duplicate profiles and try again.
```
So it's clearly generating the same profile twice, but I have no idea why yet.

**Comment by kentcb** [comment]
In case it wasn't obvious, I'm blocked because even forcing a rebuild gives me the same error.

**Comment by godrei** [comment]
Hi @vanwagonet , we have released a new version: [1.3.0](
https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.3.0), could you please check if it solves your issue?

**Comment by vanwagonet** [comment]
Our workflows are using "always latest" version, and we haven't seen this problem in a while. Thanks!
